### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by rooby** [govau/design-system-components#393]
# What happened

I cannot seem to add attributes like colspan to cells in the table component.

# What I expected to happen

I expect to be able to add attributes like colspan to cells in the table component.

**Comment by alex-page** [comment]
@rooby great suggestion. As this component is still in progress we will be moving it a long in the community area. I'll leave this ticket open until the table component is implemented.

**Comment by rooby** [comment]
So where's the best place to report other table bugs?

**Comment by alex-page** [comment]
I think in the community and here as there isn't a release component yet. I might rename this ticket to new module table.

The component you are using is a prototype used in the design system website. It's not really suitable for everyones use otherwise it would be able to be installed through `npm i @gov.au/table`.

If you notice issues or expect certain functionality please let us know here or in the community 👍

**Comment by rooby** [comment]
Cool, thanks.

Potentially it could pass through attributeOptions, similar to other components.

Another couple of things I've noticed:

- You can't put a className on the TRs.
- An empty caption tag prints out if you don't pass in a caption.

**Comment by alex-page** [comment]
Thanks @rooby these are great and quite quick fixes!

**Comment by sukhrajghuman** [comment]
> I cannot seem to add attributes like colspan to cells in the table component.

Thanks for raising this. The [current implementation](https://www.npmjs.com/package/@gov.au/table) allows additional attributes such as `colspan`, `className` etc, to be added
