### ISSUE TITLE
Control Inputs - Grouping / States

### ISSUE THREAD

**Issue by HerinHentry** [govau/design-system-components#409]
Regarding Control Input https://designsystem.gov.au/components/control-input/

As per https://www.w3.org/WAI/GL/WCAG20-TECHS/H71 provide a description for groups of form controls using fieldset and legend elements.

Do we need "single checkbox", & "group controls" with fieldset?

Also, as we have examples of disabled buttons, can we provide disabled controls examples too?

**Comment by HerinHentry** [comment]
Also please check the keyboard focus of the radio buttons using the up and down arrow keys in the live demo page. The keyboard focus for radio buttons is,
Tab into the first radio button & use up/down arrow keys to go the next in the group.

**Comment by alex-page** [comment]
You are on fire @HerinHentry 🔥 

I'll try and investigate this in the coming week. We do have some tests set up with more states here:
https://uikit.service.gov.au/packages/control-input/tests/site/

However I don't see why these shouldn't be a part of the documentation website.

**Comment by alex-page** [comment]
We are going to add some additional rationale to the control input component. 

In the future we will create a fieldset component and form templates that use fieldsets.

**Comment by sarahpulis** [comment]
I'd like add my weight behind a component/guidance on grouping and labeling related form controls. After reviewing a number of DTA websites, this is a very common accessibility requirement that is being overlooked.

**Comment by adamzerella** [comment]
Since this issue was raised we have added more documentation to `control-inputs` and the other problem described is isolated to the `form` component which was recently published.

We documented form grouping in the `form` component here: https://designsystem.gov.au/components/form/#form-groups

@HerinHentry I'm going to close this issue but please reopen it if you feel like the existing `form` rationale / docs aren't following best practice
