### ISSUE TITLE
helper.js restricts extra packages

### ISSUE THREAD

**Issue by mikey0000** [govau/design-system-components#646]
# Feature Request
- [x ] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [ x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [ x] I’ve searched for any related issues and avoided creating a duplicate issue.
- [ x] I've searched the [community forums](https://community.digital.gov.au/c/designsystem) to check for related issues or feature requests

## Is this feature request relating to an existing component? Please describe.
- Component name: 
- Component version:

helper.js

```
if( !hasReact && Object.keys( packagesPKG.devDependencies ).length > 4 ) {
						error += `The module ${ module } doesn’t have the right amount of devDependencies.\n`;
					}
```

this line restricts new packages from having extra dependencies. I'm currently in the process of creating a vector package that builds a svg spritesheet so requires some extra packages to make that happen.

My suggestion is to remove this or modify this script to search for specific packages related to react.

**Comment by adamzerella** [comment]
Hi @mikey0000, good find! 

Depending on what your working on - vector package sounds pretty cool 👍 , we don't seem to enforce the number of `dependencies` that you could have for a package - could be a quick fix for now.

Originally I believe this was enforced due to package consistency but I think for now it can be removed. I should be able to fix this today, otherwise feel free to raise a PR removing this check from the tests 😄.

**Comment by mikey0000** [comment]
Brilliant! Might be easier for you to do and review with your team as its definitely something that could use some tool sharpening time on. As for the vector package watch this space. 😄

**Comment by adamzerella** [comment]
Sure thing! looking forward to it @mikey0000 💯
